# Generated by Django 4.2.5 on 2023-11-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_name', models.CharField(max_length=100)),
                ('cs_duration', models.CharField(max_length=50)),
                ('cs_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cs_syllabus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_address', models.CharField(max_length=200)),
                ('tr_gender', models.CharField(max_length=200)),
                ('tr_age', models.IntegerField()),
                ('tr_phone', models.CharField(max_length=50)),
                ('tr_image', models.ImageField(null=True, upload_to='image/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution_app.coursemodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudntModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_address', models.CharField(max_length=200)),
                ('std_gender', models.CharField(max_length=200)),
                ('Std_age', models.IntegerField()),
                ('std_phone', models.IntegerField()),
                ('std_image', models.ImageField(null=True, upload_to='image/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution_app.coursemodel')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
