# Generated by Django 4.2.5 on 2023-11-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
