# Generated by Django 4.2.5 on 2023-11-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
