# Generated by Django 4.2.5 on 2023-11-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0007_coursemodel_students_coursemodel_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='studntmodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution_app.departmentmodel'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tution_app.departmentmodel'),
        ),
    ]
