# Generated by Django 4.2.5 on 2023-11-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0009_teacherattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='students',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='teachers',
        ),
    ]
