# Generated by Django 4.2.5 on 2023-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0010_remove_coursemodel_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='students',
            field=models.ManyToManyField(blank=True, to='tution_app.studntmodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='tution_app.teachermodel'),
        ),
    ]
