# Generated by Django 4.2.5 on 2023-11-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0011_coursemodel_students_coursemodel_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_for',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
