# Generated by Django 4.2.5 on 2023-11-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0013_studentattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
