# Generated by Django 4.2.5 on 2023-11-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0017_remove_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution_app.coursemodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tution_app.teachermodel')),
            ],
        ),
    ]
