# Generated by Django 4.2.5 on 2023-11-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0018_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studntmodel',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='assignments/'),
        ),
    ]
