# Generated by Django 4.2.5 on 2023-11-07 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0019_studntmodel_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tution_app.studntmodel'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submitted_files/'),
        ),
    ]
