# Generated by Django 4.2.5 on 2023-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0020_assignment_submitted_by_assignment_submitted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
