# Generated by Django 4.2.5 on 2023-11-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0021_assignment_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studntmodel',
            name='course',
        ),
    ]
