# Generated by Django 4.2.5 on 2023-11-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution_app', '0025_studntmodel_assign_tchr_studntmodel_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studntmodel',
            name='assign_tchr',
        ),
        migrations.RemoveField(
            model_name='studntmodel',
            name='course',
        ),
    ]
